<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Resources\file_signatures.json" LogicalName="file_signatures.json" Link="Resources\file_signatures.json" />
    <EmbeddedResource Include="..\Resources\mimeTypes.json" LogicalName="mimeTypes.json" Link="Resources\mimeTypes.json" />
  </ItemGroup>

</Project>
