<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Resources\file_signatures.csv" LogicalName="file_signatures.csv" Link="Resources\file_signatures.csv" />
    <EmbeddedResource Include="..\Resources\mime.types" LogicalName="mime.types" Link="Resources\mime.types" />
  </ItemGroup>

</Project>
